version: '3.7'

services:
  single-node1:
    container_name: single-node1
    image: tharsishq/evmos:latest
    restart: always
    command:
      - ./evmos-setup.sh
    ports:
      - 8545:8545
      - 26660:26660
    volumes:
      - ./evmos-setup.sh:/evmos-setup.sh
      - ./evmos-datadir:/tmp/evmos-datadir
      retries: 5

