version: '3.7'

services:
  single-node1:
    container_name: single-node1
    image: royki/evmos:v0.0.2
    restart: always
    command:
      - ./single-node-start.sh
    ports:
      - 8545:8545
      - 26660:26660
    volumes:
      - ./evmos-dir:/tmp
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5
