---
# defaults file for ew_docker

# Docker var
docker_pkg_name: "docker"
docker_edition: "ce"
docker_pkg_ce: "docker-{{ docker_edition }}"
docker_gpg_key_url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

# Docker compose
docker_compose_version: "1.26.0"
docker_compose_path: "/usr/local/bin/docker-compose"
docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
